// src/syntagmax/extractors/text.lark
?start: section

section: "[<" header body? ">]"

header: (directive | skip)*
skip: /.(?!(?:>>>|>]|\[<))/s

directive: id_directive | type_directive

id_directive: "ID" "=" AID
type_directive: "TYPE" "=" ATYPE

AID: /[a-zA-Z0-9-]+/
ATYPE: /[a-zA-Z0-9-]+/
REVISION: /[a-zA-Z0-9-]+/

body: ">>>" [body_content]
body_content: /(.|\n)+?(?=>])/s

%import common.WS
%ignore WS
